"""Git hooks setup - automatically configure Cloudflare deployment triggers for agents."""

import stat
from pathlib import Path
from typing import Optional

import structlog

from core.config import get_settings

logger = structlog.get_logger(__name__)

# Wrangler deploys run against product repo conventions:
#   frontend/ -> Cloudflare Pages, backend/ (with wrangler.toml) -> Worker/Container
DEPLOY_SNIPPET = """    if [ -d frontend ]; then
        echo '🚀 Deploying frontend to Cloudflare Pages...'
        npx -y wrangler pages deploy frontend --project-name "$(basename "$PWD")-frontend" --branch main && echo '✓ Pages deployment done' || echo '✗ Pages deployment failed'
    fi
    if [ -f backend/wrangler.toml ]; then
        echo '🚀 Deploying backend to Cloudflare...'
        (cd backend && npx -y wrangler deploy) && echo '✓ Backend deployment done' || echo '✗ Backend deployment failed'
    fi
"""

ACTIONS_WORKFLOW = """name: Auto Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy frontend to Cloudflare Pages
        if: hashFiles('frontend') != ''
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy frontend --project-name=${{ github.event.repository.name }}-frontend --branch main
        continue-on-error: true

      - name: Deploy backend to Cloudflare
        if: hashFiles('backend/wrangler.toml') != ''
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: backend
          command: deploy
        continue-on-error: true
"""


class GitHooksManager:
    """Manage git hooks for automatic Cloudflare deployments."""

    def __init__(self, repo_root: Optional[Path] = None):
        self.settings = get_settings()
        if repo_root:
            self.repo_root = repo_root
        else:
            self.repo_root = self._find_git_root()
        self.hooks_dir = self.repo_root / ".git" / "hooks" if self.repo_root else None

    def _find_git_root(self) -> Optional[Path]:
        """Find git repository root."""
        current = Path.cwd()
        for path in [current] + list(current.parents):
            if (path / ".git").exists():
                return path
        return None

    def _configured(self) -> bool:
        return bool(self.settings.cloudflare_api_key and self.settings.cloudflare_email)

    def setup_post_push_hook(self) -> dict:
        """
        Set up post-push git hook to trigger Cloudflare deployments.
        Returns dict with setup status.
        """
        if not self.hooks_dir or not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        if not self._configured():
            return {
                "success": False,
                "error": "Cloudflare credentials not configured (CLOUDFLARE_API_KEY + CLOUDFLARE_EMAIL)",
            }

        try:
            self.hooks_dir.mkdir(parents=True, exist_ok=True)
            hook_file = self.hooks_dir / "post-push"

            hook_content = "#!/bin/bash\n"
            hook_content += "# Auto-generated by Autonomous AI Company\n"
            hook_content += "# This hook triggers Cloudflare deployments after git push\n\n"

            hook_content += "echo '🚀 Post-push hook: Checking for deployments...'\n\n"

            # Check if push was to main/master branch
            hook_content += "while read local_ref local_sha remote_ref remote_sha\n"
            hook_content += "do\n"
            hook_content += "    if [[ \"$remote_ref\" == \"refs/heads/main\" ]] || [[ \"$remote_ref\" == \"refs/heads/master\" ]]; then\n"
            hook_content += "        echo '📦 Push detected to main/master branch'\n"
            hook_content += DEPLOY_SNIPPET
            hook_content += "    fi\n"
            hook_content += "done\n"

            hook_content += "echo '✅ Post-push hook completed'\n"

            # Write hook file
            hook_file.write_text(hook_content, encoding="utf-8")

            # Make executable
            hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)

            logger.info("git_hook_created", hook="post-push", file=str(hook_file))
            return {
                "success": True,
                "hook_file": str(hook_file),
            }
        except Exception as e:
            logger.error("git_hook_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_post_commit_hook(self) -> dict:
        """
        Set up post-commit git hook (alternative to post-push).
        Triggers Cloudflare deployments after commits to main branch.
        """
        if not self.hooks_dir or not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        if not self._configured():
            return {
                "success": False,
                "error": "Cloudflare credentials not configured",
            }

        try:
            self.hooks_dir.mkdir(parents=True, exist_ok=True)
            hook_file = self.hooks_dir / "post-commit"

            hook_content = "#!/bin/bash\n"
            hook_content += "# Auto-generated by Autonomous AI Company\n"
            hook_content += "# This hook triggers Cloudflare deployments after commits\n\n"

            hook_content += "BRANCH=$(git rev-parse --abbrev-ref HEAD)\n"
            hook_content += "if [[ \"$BRANCH\" == \"main\" ]] || [[ \"$BRANCH\" == \"master\" ]]; then\n"
            hook_content += "    echo '🚀 Post-commit hook: Main branch commit detected'\n"
            hook_content += DEPLOY_SNIPPET
            hook_content += "fi\n"

            # Write hook file
            hook_file.write_text(hook_content, encoding="utf-8")

            # Make executable
            hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)

            logger.info("git_hook_created", hook="post-commit", file=str(hook_file))
            return {
                "success": True,
                "hook_file": str(hook_file),
            }
        except Exception as e:
            logger.error("git_hook_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_github_actions_workflow(self) -> dict:
        """
        Create/update GitHub Actions workflow for automatic Cloudflare deployments.
        This is better than git hooks for CI/CD. Requires repo secrets:
        CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID.
        """
        if not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        try:
            workflows_dir = self.repo_root / ".github" / "workflows"
            workflows_dir.mkdir(parents=True, exist_ok=True)

            workflow_file = workflows_dir / "auto-deploy.yml"

            # Check if workflow already exists
            if workflow_file.exists():
                existing = workflow_file.read_text()
                if "Auto Deploy" in existing:
                    logger.info("github_workflow_exists", file=str(workflow_file))
                    return {
                        "success": True,
                        "workflow_file": str(workflow_file),
                        "message": "Workflow already exists, not overwriting",
                    }

            workflow_file.write_text(ACTIONS_WORKFLOW, encoding="utf-8")
            logger.info("github_workflow_created", file=str(workflow_file))

            return {
                "success": True,
                "workflow_file": str(workflow_file),
            }
        except Exception as e:
            logger.error("github_workflow_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_all_hooks(self) -> dict:
        """Set up all available hooks (GitHub Actions preferred, git hooks as fallback)."""
        results = {}

        # Try GitHub Actions first (best for CI/CD)
        github_result = self.setup_github_actions_workflow()
        results["github_actions"] = github_result

        # Also set up git hooks as backup
        post_push_result = self.setup_post_push_hook()
        results["post_push_hook"] = post_push_result

        return {
            "success": github_result.get("success") or post_push_result.get("success"),
            "results": results,
        }
