"""Git hooks setup - automatically configure deployment hooks for agents."""

import stat
from pathlib import Path
from typing import Optional

import structlog

from core.config import get_settings

logger = structlog.get_logger(__name__)


class GitHooksManager:
    """Manage git hooks for automatic deployments."""

    def __init__(self, repo_root: Optional[Path] = None):
        self.settings = get_settings()
        if repo_root:
            self.repo_root = repo_root
        else:
            self.repo_root = self._find_git_root()
        self.hooks_dir = self.repo_root / ".git" / "hooks" if self.repo_root else None

    def _find_git_root(self) -> Optional[Path]:
        """Find git repository root."""
        current = Path.cwd()
        for path in [current] + list(current.parents):
            if (path / ".git").exists():
                return path
        return None

    def setup_post_push_hook(self) -> dict:
        """
        Set up post-push git hook to trigger deployments.
        Returns dict with setup status.
        """
        if not self.hooks_dir or not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        try:
            self.hooks_dir.mkdir(parents=True, exist_ok=True)
            hook_file = self.hooks_dir / "post-push"

            railway_hook = self.settings.railway_deploy_hook_url.strip()
            vercel_hook = self.settings.vercel_deploy_hook_url.strip()

            if not railway_hook and not vercel_hook:
                return {
                    "success": False,
                    "error": "No deploy hook URLs configured (RAILWAY_DEPLOY_HOOK_URL or VERCEL_DEPLOY_HOOK_URL)",
                }

            hook_content = "#!/bin/bash\n"
            hook_content += "# Auto-generated by Autonomous AI Company\n"
            hook_content += "# This hook triggers deployments after git push\n\n"

            hook_content += "echo '🚀 Post-push hook: Checking for deployments...'\n\n"

            # Check if push was to main/master branch
            hook_content += "while read local_ref local_sha remote_ref remote_sha\n"
            hook_content += "do\n"
            hook_content += "    if [[ \"$remote_ref\" == \"refs/heads/main\" ]] || [[ \"$remote_ref\" == \"refs/heads/master\" ]]; then\n"
            hook_content += "        echo '📦 Push detected to main/master branch'\n\n"

            if railway_hook:
                hook_content += f"        echo '🚂 Triggering Railway deployment...'\n"
                hook_content += f"        curl -fsSL -X POST \"{railway_hook}\" && echo '✓ Railway deployment triggered' || echo '✗ Railway deployment failed'\n\n"

            if vercel_hook:
                hook_content += f"        echo '▲ Triggering Vercel deployment...'\n"
                hook_content += f"        curl -fsSL -X POST \"{vercel_hook}\" && echo '✓ Vercel deployment triggered' || echo '✗ Vercel deployment failed'\n\n"

            hook_content += "    fi\n"
            hook_content += "done\n"

            hook_content += "echo '✅ Post-push hook completed'\n"

            # Write hook file
            hook_file.write_text(hook_content, encoding="utf-8")

            # Make executable
            hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)

            logger.info("git_hook_created", hook="post-push", file=str(hook_file))
            return {
                "success": True,
                "hook_file": str(hook_file),
                "railway_configured": bool(railway_hook),
                "vercel_configured": bool(vercel_hook),
            }
        except Exception as e:
            logger.error("git_hook_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_post_commit_hook(self) -> dict:
        """
        Set up post-commit git hook (alternative to post-push).
        Triggers deployments after commits to main branch.
        """
        if not self.hooks_dir or not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        try:
            self.hooks_dir.mkdir(parents=True, exist_ok=True)
            hook_file = self.hooks_dir / "post-commit"

            railway_hook = self.settings.railway_deploy_hook_url.strip()
            vercel_hook = self.settings.vercel_deploy_hook_url.strip()

            if not railway_hook and not vercel_hook:
                return {
                    "success": False,
                    "error": "No deploy hook URLs configured",
                }

            hook_content = "#!/bin/bash\n"
            hook_content += "# Auto-generated by Autonomous AI Company\n"
            hook_content += "# This hook triggers deployments after commits\n\n"

            hook_content += "BRANCH=$(git rev-parse --abbrev-ref HEAD)\n"
            hook_content += "if [[ \"$BRANCH\" == \"main\" ]] || [[ \"$BRANCH\" == \"master\" ]]; then\n"
            hook_content += "    echo '🚀 Post-commit hook: Main branch commit detected'\n\n"

            if railway_hook:
                hook_content += f"    echo '🚂 Triggering Railway deployment...'\n"
                hook_content += f"    curl -fsSL -X POST \"{railway_hook}\" > /dev/null 2>&1 && echo '✓ Railway deployment triggered' || echo '✗ Railway deployment failed'\n\n"

            if vercel_hook:
                hook_content += f"    echo '▲ Triggering Vercel deployment...'\n"
                hook_content += f"    curl -fsSL -X POST \"{vercel_hook}\" > /dev/null 2>&1 && echo '✓ Vercel deployment triggered' || echo '✗ Vercel deployment failed'\n\n"

            hook_content += "fi\n"

            # Write hook file
            hook_file.write_text(hook_content, encoding="utf-8")

            # Make executable
            hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)

            logger.info("git_hook_created", hook="post-commit", file=str(hook_file))
            return {
                "success": True,
                "hook_file": str(hook_file),
                "railway_configured": bool(railway_hook),
                "vercel_configured": bool(vercel_hook),
            }
        except Exception as e:
            logger.error("git_hook_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_github_actions_workflow(self) -> dict:
        """
        Create/update GitHub Actions workflow for automatic deployments.
        This is better than git hooks for CI/CD.
        """
        if not self.repo_root:
            return {
                "success": False,
                "error": "Not in a git repository",
            }

        try:
            workflows_dir = self.repo_root / ".github" / "workflows"
            workflows_dir.mkdir(parents=True, exist_ok=True)

            workflow_file = workflows_dir / "auto-deploy.yml"

            railway_hook = self.settings.railway_deploy_hook_url.strip()
            vercel_hook = self.settings.vercel_deploy_hook_url.strip()

            workflow_content = """name: Auto Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
"""

            if railway_hook:
                workflow_content += f"""
      - name: Deploy to Railway
        run: |
          echo "🚂 Deploying to Railway..."
          HOOK_URL="${{{{ secrets.RAILWAY_DEPLOY_HOOK_URL || '{railway_hook}' }}}}"
          if [ -z "$HOOK_URL" ]; then
            echo "Warning: Railway deploy hook URL not configured"
            exit 0
          fi
          curl -fsSL -X POST "$HOOK_URL" || echo "Railway deployment hook failed (non-critical)"
        continue-on-error: true
"""

            if vercel_hook:
                workflow_content += f"""
      - name: Deploy to Vercel
        run: |
          echo "▲ Deploying to Vercel..."
          HOOK_URL="${{{{ secrets.VERCEL_DEPLOY_HOOK_URL || '{vercel_hook}' }}}}"
          if [ -z "$HOOK_URL" ]; then
            echo "Warning: Vercel deploy hook URL not configured"
            exit 0
          fi
          curl -fsSL -X POST "$HOOK_URL" || echo "Vercel deployment hook failed (non-critical)"
        continue-on-error: true
"""

            # Check if workflow already exists
            if workflow_file.exists():
                existing = workflow_file.read_text()
                if "Auto Deploy" in existing:
                    logger.info("github_workflow_exists", file=str(workflow_file))
                    return {
                        "success": True,
                        "workflow_file": str(workflow_file),
                        "message": "Workflow already exists, not overwriting",
                    }

            workflow_file.write_text(workflow_content, encoding="utf-8")
            logger.info("github_workflow_created", file=str(workflow_file))

            return {
                "success": True,
                "workflow_file": str(workflow_file),
                "railway_configured": bool(railway_hook),
                "vercel_configured": bool(vercel_hook),
            }
        except Exception as e:
            logger.error("github_workflow_setup_failed", error=str(e))
            return {
                "success": False,
                "error": str(e),
            }

    def setup_all_hooks(self) -> dict:
        """Set up all available hooks (GitHub Actions preferred, git hooks as fallback)."""
        results = {}

        # Try GitHub Actions first (best for CI/CD)
        github_result = self.setup_github_actions_workflow()
        results["github_actions"] = github_result

        # Also set up git hooks as backup
        post_push_result = self.setup_post_push_hook()
        results["post_push_hook"] = post_push_result

        return {
            "success": github_result.get("success") or post_push_result.get("success"),
            "results": results,
        }
